// Action Types
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';

export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';

export const VIEW_COUNT_INCREMENT_REQUEST = 'VIEW_COUNT_INCREMENT_REQUEST';
export const VIEW_COUNT_INCREMENT_SUCCESS = 'VIEW_COUNT_INCREMENT_SUCCESS';
export const VIEW_COUNT_INCREMENT_FAILURE = 'VIEW_COUNT_INCREMENT_FAILURE';

export const FETCH_IMAGE_REQUEST = 'FETCH_IMAGE_REQUEST';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const FETCH_IMAGE_FAILURE = 'FETCH_IMAGE_FAILURE';

export const FETCH_ALL_IMAGES_REQUEST = 'FETCH_ALL_IMAGES_REQUEST';
export const FETCH_ALL_IMAGES_SUCCESS = 'FETCH_ALL_IMAGES_SUCCESS';
export const FETCH_ALL_IMAGES_FAILURE = 'FETCH_ALL_IMAGES_FAILURE';
